#!/bin/bash
set -e

echo Running ruff src
uv run ruff check --fix src
echo Running ruff tests
uv run ruff check --fix tests
echo Running black src tests
uv run black src tests
echo Running isort src tests
uv run isort --profile black src tests
echo Running pyright src tests
uv run pyright src tests
echo Running flake8 KeyboardInterrupt check on src
uv run flake8 src --select=KBI || true
echo Linting complete!
exit 0
