#!/bin/bash
set -e

echo Running ruff check src tests
uv run ruff check --fix src tests
echo Running ruff format src tests
uv run ruff format src tests
echo Running pyright src tests
uv run pyright src tests
echo Running flake8 KeyboardInterrupt check on src
uv run flake8 src --select=KBI || true
echo Linting complete!
exit 0
