name: Documentation Issue
description: Report issues with documentation or request documentation improvements
title: "[Docs]: "
labels: ["documentation", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Use this template for:
        - Reporting unclear or incorrect documentation
        - Requesting new documentation
        - Suggesting documentation improvements
        - Reporting broken links or examples

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation issue is this?
      options:
        - Incorrect information
        - Unclear explanation
        - Missing documentation
        - Broken link
        - Outdated content
        - Typo or grammar
        - Code example doesn't work
        - API documentation
        - Tutorial request
        - Other
    validations:
      required: true

  - type: dropdown
    id: location
    attributes:
      label: Documentation Location
      description: Where is the documentation issue?
      options:
        - README.md
        - CONTRIBUTING.md
        - CHANGELOG.md
        - examples/README.md
        - Code comments/docstrings
        - GitHub wiki
        - PyPI page
        - Other (specify below)
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current Documentation
      description: |
        Quote or describe the current documentation that needs improvement.
        Include line numbers or section names if applicable.
      placeholder: |
        Current text: "..."
        Location: README.md, line 42, section "Installation"
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: Issue Description
      description: What is wrong or unclear about the current documentation?
      placeholder: Explain what needs to be fixed or improved...
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How should the documentation be improved?
      placeholder: |
        Suggested text: "..."
        or
        Explanation of what should be documented...
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: Who is affected by this documentation issue?
      placeholder: |
        - New users trying to install
        - Contributors setting up dev environment
        - Users of specific features
        - etc.

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references.
      placeholder: Links to related docs, screenshots showing the issue, etc.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched for similar documentation issues
          required: true
        - label: I have checked that this documentation still exists in the latest version
          required: true
