"""
NixOS support for the Clang/LLVM toolchain (GitHub issue #55).

NixOS has no FHS -- there is no ``/usr/lib``, so a bundled toolchain that ships
headers-only sysroot data cannot locate the C/C++ standard library headers or
runtime libraries on its own. Clang's driver auto-loads a per-binary config
file (``<bindir>/<driver-basename>.cfg``), so this module discovers the
system's Nix-provided gcc toolchain and writes ``clang.cfg`` / ``clang++.cfg``
files that supply the flags needed to compile and link successfully.

This module is import-light by design (stdlib only) so it can be imported
lazily from hot paths without pulling in the rest of the package.
"""

import logging
import os
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path

logger = logging.getLogger(__name__)

# First line written to every generated cfg file. Used both as a header and as
# a marker to detect "this file was generated by us" on a later run.
NIXOS_CFG_MARKER = (
    "# Generated by clang-tool-chain -- NixOS support (issue #55). Regenerate with: clang-tool-chain install clang"
)

# Opt-out environment variable: set to "1" to disable NixOS cfg generation entirely.
NO_CFG_ENV_VAR = "CLANG_TOOL_CHAIN_NO_NIXOS_CFG"

# Fallback nix-ld shared library directory used by NixOS's `programs.nix-ld` module
# when NIX_LD_LIBRARY_PATH is not set in the environment.
_NIX_LD_FALLBACK_DIR = "/run/current-system/sw/share/nix-ld/lib"

# Marker file present on every NixOS install. Kept as a module-level path so
# tests can monkeypatch it instead of touching the real filesystem.
_NIXOS_MARKER_PATH = Path("/etc/NIXOS")

_SUBPROCESS_TIMEOUT_SECS = 10


def is_nixos() -> bool:
    """True when running on NixOS.

    Detected via the presence of ``/etc/NIXOS`` (a marker file every NixOS
    install carries), or via the ``NIX_LD`` / ``NIX_LD_LIBRARY_PATH``
    environment variables set by NixOS's ``programs.nix-ld`` module (also
    present in nix-ld-enabled non-NixOS environments, which want the same
    handling).
    """
    if _NIXOS_MARKER_PATH.exists():
        return True
    return bool(os.environ.get("NIX_LD") or os.environ.get("NIX_LD_LIBRARY_PATH"))


@dataclass(frozen=True)
class NixToolchain:
    """Paths discovered by probing the system ``gcc``/``g++`` on NixOS."""

    gcc_root: str
    gcc_install_dir: str
    gcc_lib_dir: str
    libgcc_dir: str
    glibc_lib_dir: str
    glibc_include_dir: str  # "" when not discovered
    nix_ld_lib_dirs: tuple[str, ...]


def _probe_stdout(gcc: str, *args: str) -> str | None:
    """Run ``gcc <args>`` and return stripped stdout, or None on any failure."""
    try:
        result = subprocess.run(
            [gcc, *args],
            capture_output=True,
            text=True,
            timeout=_SUBPROCESS_TIMEOUT_SECS,
            check=False,
        )
    except (OSError, subprocess.SubprocessError):
        return None
    if result.returncode != 0:
        return None
    output = result.stdout.strip()
    return output or None


def _resolved_path(candidate: str | None) -> str | None:
    """Return *candidate* if it looks like a resolved absolute path.

    ``gcc -print-file-name=X`` echoes back the bare ``X`` argument when it
    cannot resolve the file, so a non-absolute result means "not found".
    """
    if candidate and os.path.isabs(candidate):
        return candidate
    return None


def _discover_glibc_include_dir(gcc: str, gcc_root: str) -> str:
    """Parse ``gcc -E -Wp,-v -xc /dev/null`` stderr for the glibc-dev include dir.

    Returns the first entry in the ``#include <...>`` search list that is not
    rooted under *gcc_root* (i.e. the glibc-dev include directory rather than
    one of gcc's own bundled include directories), or "" when not found.
    """
    try:
        result = subprocess.run(
            [gcc, "-E", "-Wp,-v", "-xc", "/dev/null"],
            capture_output=True,
            text=True,
            timeout=_SUBPROCESS_TIMEOUT_SECS,
            check=False,
        )
    except (OSError, subprocess.SubprocessError):
        return ""

    in_angle_bracket_list = False
    candidates: list[str] = []
    for raw_line in result.stderr.splitlines():
        line = raw_line.strip()
        if line.startswith("#include <...>") and "search starts here" in line:
            in_angle_bracket_list = True
            continue
        if line == "End of search list.":
            break
        if in_angle_bracket_list and line:
            candidates.append(line)

    for candidate in candidates:
        if not candidate.startswith(gcc_root):
            return candidate
    return ""


def _discover_nix_ld_lib_dirs() -> tuple[str, ...]:
    raw = os.environ.get("NIX_LD_LIBRARY_PATH", "")
    dirs = [entry for entry in raw.split(":") if entry]
    if dirs:
        return tuple(dirs)
    if os.path.isdir(_NIX_LD_FALLBACK_DIR):
        return (_NIX_LD_FALLBACK_DIR,)
    return ()


def discover_nix_toolchain(gcc: str | None = None) -> NixToolchain | None:
    """Probe the system gcc for the paths needed to build a NixOS clang.cfg.

    Args:
        gcc: Path/name of the gcc binary to probe. Defaults to
            ``shutil.which("gcc")`` or ``shutil.which("g++")``.

    Returns:
        A populated ``NixToolchain``, or None when gcc is absent or probing
        fails to resolve the essential paths (gcc install dir, glibc lib dir,
        libstdc++ dir).
    """
    resolved_gcc = gcc or shutil.which("gcc") or shutil.which("g++")
    if not resolved_gcc:
        return None

    libgcc_path = _resolved_path(_probe_stdout(resolved_gcc, "-print-libgcc-file-name"))
    if not libgcc_path:
        logger.warning(f"NixOS: could not resolve libgcc path via '{resolved_gcc} -print-libgcc-file-name'")
        return None
    gcc_install_dir = os.path.dirname(libgcc_path)
    gcc_install_dir_path = Path(gcc_install_dir)
    if len(gcc_install_dir_path.parents) < 4:
        logger.warning(f"NixOS: unexpected gcc install layout, cannot derive gcc_root from {gcc_install_dir}")
        return None
    gcc_root = str(gcc_install_dir_path.parents[3])

    crt1_path = _resolved_path(_probe_stdout(resolved_gcc, "-print-file-name=crt1.o"))
    if not crt1_path:
        logger.warning(f"NixOS: could not resolve crt1.o via '{resolved_gcc} -print-file-name=crt1.o'")
        return None
    glibc_lib_dir = os.path.dirname(crt1_path)

    libstdcxx_path = _resolved_path(_probe_stdout(resolved_gcc, "-print-file-name=libstdc++.so.6"))
    if not libstdcxx_path:
        logger.warning(f"NixOS: could not resolve libstdc++.so.6 via '{resolved_gcc} -print-file-name=libstdc++.so.6'")
        return None
    gcc_lib_dir = os.path.dirname(libstdcxx_path)

    libgcc_s_path = _resolved_path(_probe_stdout(resolved_gcc, "-print-file-name=libgcc_s.so.1"))
    libgcc_dir = os.path.dirname(libgcc_s_path) if libgcc_s_path else gcc_lib_dir

    glibc_include_dir = _discover_glibc_include_dir(resolved_gcc, gcc_root)
    nix_ld_lib_dirs = _discover_nix_ld_lib_dirs()

    return NixToolchain(
        gcc_root=gcc_root,
        gcc_install_dir=gcc_install_dir,
        gcc_lib_dir=gcc_lib_dir,
        libgcc_dir=libgcc_dir,
        glibc_lib_dir=glibc_lib_dir,
        glibc_include_dir=glibc_include_dir,
        nix_ld_lib_dirs=nix_ld_lib_dirs,
    )


def _dedupe_existing_dirs(dirs: list[str]) -> list[str]:
    """Dedupe *dirs* preserving order, dropping empties and non-existent dirs."""
    seen: set[str] = set()
    result: list[str] = []
    for directory in dirs:
        if not directory or directory in seen:
            continue
        if not os.path.isdir(directory):
            continue
        seen.add(directory)
        result.append(directory)
    return result


def build_config_lines(toolchain: NixToolchain, compiler_rt_lib_dir: str | None = None) -> list[str]:
    """Build the lines of a clang ``.cfg`` file for NixOS support.

    Args:
        toolchain: Discovered system gcc toolchain paths.
        compiler_rt_lib_dir: Directory containing ``libclang_rt.*`` shared
            libraries for this clang install (e.g.
            ``<clang_root>/lib/clang/<N>/lib/<triple>``). When given, an rpath
            entry is added so sanitizer runtimes (ASan, etc.) can be found at
            runtime. Omitted when not given/found.

    Returns:
        The complete list of lines for the cfg file, including the header
        comment block. Does NOT include trailing newlines.

    Note:
        Deliberately never emits ``-Wl,-dynamic-linker``: leaving the ELF
        interpreter at its default lets the nix-ld shim run and resolve
        transitive shared-library dependencies via ``NIX_LD_LIBRARY_PATH``,
        which is issue #55's stated first preference.
    """
    lines: list[str] = [
        NIXOS_CFG_MARKER,
        "#",
        "# NixOS has no FHS (there is no /usr/lib), so clang cannot locate the C/C++",
        "# standard library headers or runtime libraries without explicit help. This",
        "# file is a clang driver config file -- auto-loaded from <bindir>/<driver>.cfg",
        "# by clang itself -- that supplies the flags needed to compile and link",
        "# successfully on NixOS. See https://github.com/zackees/clang-tool-chain/issues/55",
        "#",
        f"# Opt-out: set {NO_CFG_ENV_VAR}=1 in the environment before running",
        "# `clang-tool-chain install clang` to stop generating/regenerating this file.",
        "#",
        "# Deliberately NOT pinning -Wl,-dynamic-linker: leaving the ELF interpreter at",
        "# its default allows the nix-ld shim (programs.nix-ld) to run and resolve",
        "# transitive shared-library dependencies via NIX_LD_LIBRARY_PATH. Pinning our",
        "# own dynamic linker path here would bypass nix-ld -- issue #55's identified",
        "# first preference.",
        "",
        f"--gcc-toolchain={toolchain.gcc_root}",
        f"-B{toolchain.gcc_install_dir}",
        f"-B{toolchain.glibc_lib_dir}",
    ]

    if toolchain.glibc_include_dir:
        lines.append(f"-idirafter {toolchain.glibc_include_dir}")

    # <gcc_root>/lib holds the archives that are absent from the split-out
    # "gcc-<ver>-lib" output: libstdc++.a, libasan.a, libatomic.a and friends.
    # Without it, -static-libstdc++ (used by `clang-tool-chain compile-native`)
    # fails with "cannot find -lstdc++".
    gcc_root_lib_dir = os.path.join(toolchain.gcc_root, "lib")
    lib_dirs = _dedupe_existing_dirs(
        [
            toolchain.gcc_install_dir,
            toolchain.gcc_lib_dir,
            toolchain.libgcc_dir,
            gcc_root_lib_dir,
            toolchain.glibc_lib_dir,
        ]
    )
    lines.extend(f"-L{directory}" for directory in lib_dirs)

    rpath_candidates = [toolchain.gcc_lib_dir, toolchain.libgcc_dir, toolchain.glibc_lib_dir]
    rpath_candidates.extend(toolchain.nix_ld_lib_dirs)
    if compiler_rt_lib_dir:
        rpath_candidates.append(compiler_rt_lib_dir)
    rpath_dirs = _dedupe_existing_dirs(rpath_candidates)
    lines.extend(f"-Wl,-rpath,{directory}" for directory in rpath_dirs)

    return lines


def _discover_compiler_rt_lib_dir(clang_root: Path) -> str | None:
    """Find the directory containing compiler-rt shared libraries for this clang.

    Globs ``clang_root/lib/clang/*/lib/*/`` and returns the first directory
    containing a ``libclang_rt.*`` file, or None when not found.
    """
    clang_lib_root = clang_root / "lib" / "clang"
    if not clang_lib_root.is_dir():
        return None
    for version_dir in sorted(clang_lib_root.iterdir()):
        lib_dir = version_dir / "lib"
        if not lib_dir.is_dir():
            continue
        for triple_dir in sorted(lib_dir.iterdir()):
            if not triple_dir.is_dir():
                continue
            if any(triple_dir.glob("libclang_rt.*")):
                return str(triple_dir)
    return None


def _backup_and_check_skip(cfg_path: Path, content: str, *, force: bool) -> bool:
    """Handle backup-of-foreign-file and skip-if-unchanged logic.

    Returns True if the write should be skipped (content unchanged, not forced).
    """
    if not cfg_path.exists():
        return False

    try:
        existing = cfg_path.read_text()
    except OSError:
        existing = None

    if existing is None:
        return False

    existing_first_line = existing.splitlines()[0] if existing else ""
    is_ours = existing_first_line == NIXOS_CFG_MARKER

    if is_ours:
        return existing == content and not force

    backup_path = cfg_path.with_name(cfg_path.name + ".bak")
    shutil.copy2(cfg_path, backup_path)
    logger.info(f"Backed up pre-existing {cfg_path.name} to {backup_path.name} before writing NixOS clang config")
    return False


def write_nixos_clang_configs(clang_root: Path, *, force: bool = False) -> list[Path]:
    """Write ``bin/clang.cfg`` and ``bin/clang++.cfg`` with NixOS support flags.

    No-op (returns ``[]``) when:
      - not running on NixOS, or
      - ``CLANG_TOOL_CHAIN_NO_NIXOS_CFG=1`` is set, or
      - the system gcc toolchain could not be discovered (a warning is logged
        telling the user to install gcc).

    Args:
        clang_root: The clang/LLVM installation root (contains ``bin/``).
        force: Write even when the resulting content is byte-identical to
            what is already on disk. Normal behaviour skips the write in that
            case to avoid bumping the file's mtime on every install.

    Returns:
        The list of cfg file paths actually written (empty when skipped).
    """
    if not is_nixos():
        return []

    if os.environ.get(NO_CFG_ENV_VAR) == "1":
        return []

    toolchain = discover_nix_toolchain()
    if toolchain is None:
        logger.warning(
            "NixOS detected but no system gcc/g++ was found on PATH. Binaries produced by "
            "clang-tool-chain will fail to compile or link (missing libstdc++/libgcc_s/glibc "
            "headers and libraries) until a gcc is available. Add `gcc` to "
            "environment.systemPackages in your NixOS configuration.nix, or run inside "
            "`nix-shell -p gcc`, then re-run `clang-tool-chain install clang --force`."
        )
        return []

    compiler_rt_lib_dir = _discover_compiler_rt_lib_dir(clang_root)
    lines = build_config_lines(toolchain, compiler_rt_lib_dir)
    content = "\n".join(lines) + "\n"

    bin_dir = clang_root / "bin"
    written: list[Path] = []
    for cfg_name in ("clang.cfg", "clang++.cfg"):
        cfg_path = bin_dir / cfg_name
        if _backup_and_check_skip(cfg_path, content, force=force):
            continue
        bin_dir.mkdir(parents=True, exist_ok=True)
        cfg_path.write_text(content)
        logger.info(f"Wrote NixOS clang config: {cfg_path}")
        written.append(cfg_path)

    return written


def nixos_status_report(clang_root: Path | None = None) -> list[str]:
    """Return human-readable diagnostic lines about NixOS support state.

    Returns an empty list when not running on NixOS.
    """
    if not is_nixos():
        return []

    lines: list[str] = ["NixOS detected."]

    toolchain = discover_nix_toolchain()
    if toolchain is None:
        lines.append("No system gcc/g++ found -- NixOS compile/link support is NOT configured.")
        lines.append(
            "Install gcc (environment.systemPackages, or `nix-shell -p gcc`) and re-run "
            "`clang-tool-chain install clang --force`."
        )
        return lines

    lines.append(f"System gcc toolchain: {toolchain.gcc_root}")
    lines.append(f"  gcc install dir:   {toolchain.gcc_install_dir}")
    lines.append(f"  gcc lib dir:       {toolchain.gcc_lib_dir}")
    lines.append(f"  glibc lib dir:     {toolchain.glibc_lib_dir}")
    lines.append(f"  glibc include dir: {toolchain.glibc_include_dir or '(not found)'}")
    if toolchain.nix_ld_lib_dirs:
        lines.append(f"  nix-ld lib dirs:   {', '.join(toolchain.nix_ld_lib_dirs)}")
    else:
        lines.append("  nix-ld lib dirs:   (none found -- set NIX_LD_LIBRARY_PATH for full runtime resolution)")

    if clang_root is not None:
        clang_cfg = clang_root / "bin" / "clang.cfg"
        if clang_cfg.exists():
            try:
                first_line = clang_cfg.read_text().splitlines()[0]
            except OSError:
                first_line = ""
            if first_line == NIXOS_CFG_MARKER:
                lines.append(f"clang.cfg: generated by clang-tool-chain ({clang_cfg})")
            else:
                lines.append(f"clang.cfg: present but NOT generated by clang-tool-chain ({clang_cfg})")
        else:
            lines.append(f"clang.cfg: not present at {clang_cfg} -- run `clang-tool-chain install clang --force`")

    return lines
